sudo: required
services: 
  - docker
language: node_js
node_js:
  - "10"
cache: npm # cache node_modules
before_install:
  # install heroku CLI 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login --username="$HEROKU_USERNAME" --password=$(heroku auth:token) registry.heroku.com
script:
  - npm install
  - npm test
  - sh scripts/build.sh # build script to build the docker containers
deploy:
  provider: script
  script:
    sh scripts/deploy.sh # deploy the docker container to heroku